/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#2F4F4F',
        'on-primary': '#FFFFFF',
        'primary-container': '#4F6F6F',
        'on-primary-container': '#FFFFFF',
        'secondary': '#FF7F50',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#FFDAB9',
        'on-secondary-container': '#000000',
        'tertiary': '#B0C4DE',
        'on-tertiary': '#000000',
        'tertiary-container': '#C5D3E0',
        'on-tertiary-container': '#000000',
        'error': '#B00020',
        'on-error': '#FFFFFF',
        'error-container': '#FCD8DF',
        'on-error-container': '#000000',
        'background': '#F5F5F5',
        'on-background': '#000000',
        'surface': '#FFFFFF',
        'on-surface': '#000000',
        'surface-variant': '#E0E0E0',
        'on-surface-variant': '#000000',
        'outline': '#BDBDBD',
        'shadow': '#000000',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#FFFFFF',
        'inverse-primary': '#A6C1FF',
      },
    },
  },
  plugins: [],
};
