/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'm3-primary': 'var(--m3-primary)',
        'm3-on-primary': 'var(--m3-on-primary)',
        'm3-primary-container': 'var(--m3-primary-container)',
        'm3-on-primary-container': 'var(--m3-on-primary-container)',
        'm3-secondary': 'var(--m3-secondary)',
        'm3-on-secondary': 'var(--m3-on-secondary)',
        'm3-secondary-container': 'var(--m3-secondary-container)',
        'm3-on-secondary-container': 'var(--m3-on-secondary-container)',
        'm3-tertiary': 'var(--m3-tertiary)',
        'm3-on-tertiary': 'var(--m3-on-tertiary)',
        'm3-tertiary-container': 'var(--m3-tertiary-container)',
        'm3-on-tertiary-container': 'var(--m3-on-tertiary-container)',
        'm3-error': 'var(--m3-error)',
        'm3-on-error': 'var(--m3-on-error)',
        'm3-error-container': 'var(--m3-error-container)',
        'm3-on-error-container': 'var(--m3-on-error-container)',
        'm3-background': 'var(--m3-background)',
        'm3-on-background': 'var(--m3-on-background)',
        'm3-surface': 'var(--m3-surface)',
        'm3-on-surface': 'var(--m3-on-surface)',
        'm3-surface-variant': 'var(--m3-surface-variant)',
        'm3-on-surface-variant': 'var(--m3-on-surface-variant)',
        'm3-outline': 'var(--m3-outline)',
        'm3-shadow': 'var(--m3-shadow)',
        'm3-inverse-surface': 'var(--m3-inverse-surface)',
        'm3-inverse-on-surface': 'var(--m3-inverse-on-surface)',
        'm3-inverse-primary': 'var(--m3-inverse-primary)',
      },
    },
  },
  plugins: [],
};
